# Add the NodeJS repo so we can install NodeJS
- name: Repos | Add Chris-Lea nodejs repository
  apt_repository:
    repo: "ppa:chris-lea/node.js"
  when: (nodejs)

# Add the PHP repo, so we can install the newest PHP!
- name: Repos | Add ondrej php repository
  apt_repository:
    repo: "ppa:ondrej/php5"
  when: (newest_php) and (php)