# Let's install composer in our box!
- name: Composer | Install composer
  shell:
    curl -sS https://getcomposer.org/installer | /usr/bin/php && /bin/mv -f /home/vagrant/composer.phar /usr/local/bin/composer
    creates=/usr/local/bin/composer

# Update composer if possible.
- name: Composer | Update Composer
  shell:
    /usr/local/bin/composer self-update